/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ─── Legacy Healix tokens (kept for backward compat) ───
        forest: '#0a3935',
        orange: '#ff6b35',
        cream: '#fdfbf7',
        sage: '#c3d3d1',

        // ─── Healix Design System (from Stitch) ───
        'surface': '#f7faf6',
        'surface-dim': '#d8dbd7',
        'surface-bright': '#f7faf6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f0',
        'surface-container': '#ecefeb',
        'surface-container-high': '#e6e9e5',
        'surface-container-highest': '#e0e3df',
        'on-surface': '#181c1a',
        'on-surface-variant': '#3f4944',
        'inverse-surface': '#2d312f',
        'inverse-on-surface': '#eef2ed',
        'outline': '#6f7973',
        'outline-variant': '#bec9c2',
        'surface-tint': '#1b6b51',
        'primary': '#004532',
        'on-primary': '#ffffff',
        'primary-container': '#065f46',
        'on-primary-container': '#8bd6b7',
        'inverse-primary': '#8bd6b6',
        'primary-fixed': '#a6f2d1',
        'primary-fixed-dim': '#8bd6b6',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#00513b',
        'secondary': '#52625c',
        'on-secondary': '#ffffff',
        'secondary-container': '#d3e3dc',
        'on-secondary-container': '#566660',
        'secondary-fixed': '#d5e6df',
        'secondary-fixed-dim': '#bacac3',
        'on-secondary-fixed': '#101e1a',
        'on-secondary-fixed-variant': '#3b4a44',
        'tertiary': '#652925',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#823f3a',
        'on-tertiary-container': '#ffb4ad',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb3ac',
        'on-tertiary-fixed': '#3b0908',
        'on-tertiary-fixed-variant': '#73332f',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f7faf6',
        'on-background': '#181c1a',
        'surface-variant': '#e0e3df',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',        // 24px — primary card radius
        '2xl': '2rem',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Thmanyah Sans', 'Cairo', 'sans-serif'],
        thmanyah: ['Thmanyah Sans', 'Cairo', 'sans-serif'],
        cairo: ['Thmanyah Sans', 'Cairo', 'sans-serif'],
        tajawal: ['Thmanyah Sans', 'Cairo', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      boxShadow: {
        'healix': '0px 10px 40px rgba(6, 95, 70, 0.04)',
        'healix-md': '0px 20px 60px rgba(6, 95, 70, 0.08)',
        'healix-lg': '0px 30px 80px rgba(6, 95, 70, 0.12)',
      },
      transitionTimingFunction: {
        'premium': 'cubic-bezier(0.2, 0, 0, 1)',
      },
      animation: {
        'shimmer': 'shimmer 2s infinite linear',
        'fade-up': 'fadeUp 0.8s ease-out forwards',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}